name: Generate Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: vaibhav-dev1707
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
